name: continuous integration

on:
  push:
    branches:
      - master

jobs:
  test:
    name: Test on node ${{ matrix.node_version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]
        node_version: [10, 12]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
        with:
          ref: master

      - name: Run Test
        run: npm run test

  build:
    name: Build on node ${{ matrix.node_version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]
        node_version: [10, 12]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
        with:
          ref: master

      - name: Run Build
        run: npm run test

  package:
    name: Docker Build
    runs-on: ubuntu-18.04
    needs: [test, build]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
        with:
          ref: master

      - name: Run Docker BUild
        run: |
          docker build -t test .
          docker push hyouk/test:latest
